name: Feature Request
description: Suggest a new feature or enhancement for the DPP system
title: '[Feature]: '
labels: ['enhancement']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your proposal.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the feature or enhancement
      placeholder: What feature would you like to see?
    validations:
      required: true

  - type: dropdown
    id: affected-area
    attributes:
      label: Affected Area
      description: Which part of the system would this feature affect?
      multiple: true
      options:
        - Smart contracts (Solidity/Chaincode)
        - Backend (NestJS API)
        - Frontend (Next.js app)
        - Infrastructure/DevOps
        - CI/CD
        - Documentation
        - Build system
        - Testing infrastructure
        - Project management / meta
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or limitation you're experiencing:
        - What are you trying to accomplish?
        - What's blocking you from doing this today?
        - How does this relate to DPP's goals (traceability, authenticity, sustainability)?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: |
        Describe your proposed solution:
        - What should the feature do?
        - How should users interact with it?
        - What would the user experience be?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative approaches you've thought about
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the feature request here. This may include:
        - Mockups or wireframes
        - Examples from other systems
        - Links to relevant research or documentation
        - Use cases or user stories
        - Technical considerations
      placeholder: Add any additional information, screenshots, or links
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Needed soon)
        - Medium (Would be nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to implement this feature
          required: false
        - label: I would be willing to help test this feature
          required: false
